# Generated by Django 6.1.1 on 2026-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipe_user_alter_recipe_receipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
